server:
  port: 9003

spring:
  application:
    name: admin-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shopping-mall

service-urls:
  user-service: http://localhost:8081
  product-service: http://localhost:8082
  order-service: http://localhost:8083
